ports:
  web:
    port: 80
    expose:
      hostPort: 80   # optional, only needed if you want direct access outside tunnel
  websecure:
    port: 443
    expose:
      hostPort: 443  # optional
  metrics:
    port: 9100
    expose:
      service:
        enabled: true
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: /metrics
          prometheus.io/port: "9100"
    nodePort: 30190 

metrics:
  prometheus:
    enabled: true
    service:
      type: NodePort  
      nodePort: 30190
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"

service:
  type: NodePort  # allows outside scraping
