# traefik-values.yaml
ports:
  web:
    port: 80
    expose:
      service:
        enabled: true
    nodePort: 30080
  websecure:
    port: 443
    expose:
      service:
        enabled: true
    nodePort: 30443
  metrics:
    port: 9100
    expose:
      service:
        enabled: true
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: /metrics
          prometheus.io/port: "9100"
    nodePort: 30190

metrics:
  prometheus:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"

service:
  type: NodePort

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":9100"
