ports:
  web:
    port: 80
    expose:
      hostPort: 80       # bind directly to host port
  websecure:
    port: 443
    expose:
      hostPort: 443      # optional if you use TLS
  metrics:
    port: 9100
    expose:
      service:
        enabled: true
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: /metrics
          prometheus.io/port: "9100"
    nodePort: 30190

metrics:
  prometheus:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"

service:
  type: ClusterIP      
