ports:
  web:
    port: 80
    expose:
      hostPort: 80   # binds Traefik to localhost:80
  websecure:
    port: 443
    expose:
      hostPort: 443  # binds Traefik to localhost:443
  metrics:
    port: 9100
    expose:
      service:
        enabled: true
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: /metrics
          prometheus.io/port: "9100"

metrics:
  prometheus:
    enabled: true
    service:
      type: ClusterIP  # internal scraping only
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9100"

ingressClass:
  enabled: true
  isDefaultClass: false
  name: traefik


service:
  type: ClusterIP  # web service internal, hostPort handles external access
