# values.yaml
ports:
  web:
    port: 80
    expose:
      hostPort: 80        # binds Traefik pod directly to localhost:80
  websecure:
    port: 443
    expose:
      hostPort: 443       # binds Traefik pod directly to localhost:443
  metrics:
    port: 9100
    expose:
      service:
        enabled: true
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: /metrics
          prometheus.io/port: "9100"

additionalArguments:
  - "--entrypoints.web.address=:80"
  - "--entrypoints.websecure.address=:443"
  - "--providers.kubernetesingress"
  - "--metrics.prometheus=true"
  - "--metrics.prometheus.port=:9100"

ingressClass:
  enabled: true
  isDefaultClass: true    # all Ingresses automatically handled

service:
  type: ClusterIP          # hostPort handles external access
