apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: prometheus
  managed-by: kustomize

resources:
  - pvc.yaml
  - configmap.yaml
  - alerts.yaml
  - deployment.yaml
  - service.yaml

