apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Resource ordering: PVC before deployments
resources:
  - pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - emailer-deployment.yaml
  - emailer-service.yaml

