apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: viktutors

commonLabels:
  part-of: viktutors

commonAnnotations:
  config.kubernetes.io/origin: |
    path: kustomize/overlays/viktutors/viktutors

resources:
  - namespace.yaml
  - ../../../base/viktutors
  - configmap.yaml
  - ingress.yaml

