apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonLabels:
  part-of: monitoring

commonAnnotations:
  config.kubernetes.io/origin: |
    path: kustomize/overlays/blackbox-exporter/monitoring

resources:
  - ../../../base/blackbox-exporter

