apiVersion: v1
kind: Service
metadata:
  name: raspberrypi-exporter
  namespace: monitoring
spec:
  selector:
    app: raspberrypi-exporter
  ports:
    - name: http
      port: 8080
      targetPort: 8080
