apiVersion: v1
kind: Service
metadata:
  name: viktutors-website
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: viktutors-website
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

