apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: personal-website
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: cv.mustaci.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: personal-website
            port:
              number: 80

