apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

commonLabels:
  part-of: resume

commonAnnotations:
  config.kubernetes.io/origin: |
    path: kustomize/overlays/resume/default

resources:
  - ../../../base/resume
  - ingress.yaml

